name: Build Zygisk Module

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NDK_VER: r25c

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-${NDK_VER}-linux.zip
          unzip android-ndk-${NDK_VER}-linux.zip
          echo "NDK=$PWD/android-ndk-${NDK_VER}" >> $GITHUB_ENV

      - name: Build libzygisk.so
        run: |
          cd src/main
          $NDK/ndk-build NDK_APPLICATION_MK=../../Application.mk
          mkdir -p ../../module
          cp libs/arm64-v8a/libzygisk.so ../../module/

      - name: Pack Magisk module
        run: |
          cd module
          zip -r ../zygisk-logmute-built.zip ./*

      - name: Upload Artifact
        uses: actions/upload-artifact@V4
        with:
          name: Zygisk Module
          path: zygisk-logmute-built.zip
